name: Playwright Enterprise Tests

permissions:
  contents: read
  pages: write
  id-token: write

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        default: QA
        type: choice
        options:
          - QA
          - UAT
          - PROD

      testFile:
        description: Test File
        required: true
        default: tests/ui/alltest.spec.js

jobs:

  test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        browser:
          - chromium
          - firefox
          - webkit

    env:
      ENV: ${{ github.event.inputs.environment }}

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - run: npx playwright install --with-deps

      - name: Execute Tests
        run: |
          echo "Environment : $ENV"
          echo "Browser : ${{ matrix.browser }}"
          echo "Test : ${{ github.event.inputs.testFile }}"
          npx playwright test "${{ github.event.inputs.testFile }}" --project=${{ matrix.browser }}
        continue-on-error: true

      - name: Generate Allure
        if: always()
        run: |
          npx allure-commandline generate allure-results --clean -o allure-report

      - name: Prepare GitHub Pages
        if: always()
        run: |

          mkdir -p github-pages

          cp reports/index.html github-pages/index.html

          mkdir -p github-pages/allure
          cp -r allure-report/* github-pages/allure/ || true

          mkdir -p github-pages/playwright
          cp -r playwright-report/* github-pages/playwright/ || true

      - name: Upload Pages Artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: github-pages

  deploy:

    needs: test

    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4